Feature: Disputes (#1663)
* feature: dispute request observer
* feature: dispute protocol
* feature: add dispute protocol to router
* feature: push dispute protocol to router
* feature: injection of dispute classes
* fix: logger group for disputes
* fix: redundant-move warns
* fix: pre-commit git hook
* fix: router mock
* fix: possible redundant calculation for log
* refactor: remove redundant if-statement
* fix: logging of optional
* feature: ParachainHost_on_chain_votes
* feature: get authority id by peer id
* refactor: move SmallLruCache
* feature: dispute batches
* feature: support async processing of request in request-response protocols
* feature: runtime info aka cache of rt data
* fix: remove assert
* feature: candidate vote state
* feature: revert blocks
* feature: provisioner
* feature: extend parachain host api
* feature: request votes for selections
* feature: random disputes selection for inherent
* feature: prioritized selection of disputes for inherent
* refactor: rename some dispute coordinator methods
* fix: apply clang-format for non-formatted files
* git: fix use after move in ctor
* fix: non-initialized member
* fix: CandidateComparator::operator<
* fix: kCandidateVotesLookupKey
* fix: dispute storage
* fix: prepare import in tick of batch
* fix: candidate vote state creation
* fix: taking of waiting_for_active_disputes
* fix: handle gotten active dispute response
* fix: stream engine logging group
* fix: SendingDispute ctor
* fix: some fixes in dispute coordinator
* feature: use determined undisputed chain at finalization voting
* fix: determining of undisputed blocks
* fix: candidate votes writing
* fix: log unsupported keys
* fix: counter initialization in batch
* feature: added logger in batch
* fix: log messages in approval distribution
* feature: dispute related metrics
* feature: peer count metric
* fix: test
* fix: disputes_finality_lag metric

Signed-off-by: Dmitriy Khaustov aka xDimon <khaustov.dm@gmail.com>

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -29,10 +29,13 @@ if [ $CLANG_FORMAT_ENABLED ]; then
   fi
 fi
 
+FILES=$(git diff --staged --diff-filter=ACMR --name-only)
+
 # check c++ files' format with clang-format
 CXX_RES=0
 if [ $CLANG_FORMAT_ENABLED ]; then
-  for FILE in $(git diff-index --name-only "${BASE}" --diff-filter=ACMR | grep -e "\\.[ch]pp$"); do
+#  for FILE in $(git diff-index --name-only "${BASE}" --diff-filter=ACMR | grep -e "\\.[ch]pp$"); do
+  for FILE in $(echo "$FILES" | grep -e "\\.[ch]pp$"); do
     O_HASH=$(shasum <"${FILE}")
     F_HASH=$(${CLANG_FORMAT} --style=file "$FILE" | shasum)
     if [ "${O_HASH}" != "${F_HASH}" ]; then
@@ -47,35 +50,36 @@ if [ $CLANG_FORMAT_ENABLED ]; then
   fi
 fi
 
-# check cmake-format binary
-CMAKE_FORMAT_ENABLED=1
-CMAKE_FORMAT=$(which cmake-format)
-if [ -z "${CMAKE_FORMAT}" ]; then
-  echo "Command cmake-format is not found" >&2
-  echo "Please, install cmake-format version 15 to enable checkup cmake-files formatting over git pre-commit hook" >&2
-  CMAKE_FORMAT_ENABLED=0
-fi
-
-# check cmake-files' format with cmake-format
-CMAKE_RES=0
-if [ $CMAKE_FORMAT_ENABLED ]; then
-  for FILE in $(git diff-index --name-only "${BASE}" --diff-filter=ACMR | grep -e "\(\(CMakeLists\\.txt\)\|\(\\.cmake\)\)$"); do
-    O_HASH=$(shasum <"${FILE}")
-    F_HASH=$(${CMAKE_FORMAT} --style=file "$FILE" | shasum)
-    if [ "${O_HASH}" != "${F_HASH}" ]; then
-      echo "File looks nonformatted: $FILE"
-      CMAKE_RES=1
-    fi
-  done
-
-  if [ $CMAKE_RES = 1 ]; then
-    CMAKE_FORMAT_VERSION_FULL=$($CMAKE_FORMAT --version)
-    echo "Used cmake-format version $CMAKE_FORMAT_VERSION_FULL" >&2
-  fi
-fi
+## check cmake-format binary
+#CMAKE_FORMAT_ENABLED=1
+#CMAKE_FORMAT=$(which cmake-format)
+#if [ -z "${CMAKE_FORMAT}" ]; then
+#  echo "Command cmake-format is not found" >&2
+#  echo "Please, install cmake-format version 15 to enable checkup cmake-files formatting over git pre-commit hook" >&2
+#  CMAKE_FORMAT_ENABLED=0
+#fi
+#
+## check cmake-files' format with cmake-format
+#CMAKE_RES=0
+#if [ $CMAKE_FORMAT_ENABLED ]; then
+#  for FILE in $(echo "$FILES" | grep -e "\(\(CMakeLists\\.txt\)\|\(\\.cmake\)\)$"); do
+#    O_HASH=$(shasum <"${FILE}")
+#    F_HASH=$(${CMAKE_FORMAT} "$FILE" | shasum)
+#    if [ "${O_HASH}" != "${F_HASH}" ]; then
+#      echo "File looks nonformatted: $FILE"
+#      CMAKE_RES=1
+#    fi
+#  done
+#
+#  if [ $CMAKE_RES = 1 ]; then
+#    CMAKE_FORMAT_VERSION_FULL=$($CMAKE_FORMAT --version)
+#    echo "Used cmake-format version $CMAKE_FORMAT_VERSION_FULL" >&2
+#  fi
+#fi
 
 # result of checks
-if [ $CXX_RES = 1 ] || [ $CMAKE_RES = 1 ]; then
+if [ "$CXX_RES" = "1" ] || [ "$CMAKE_RES" = "1" ]; then
+  echo "Formatter required" >&2
   exit 1
 fi
 
