Runtime cache build packet - first iteration

diff --git a/housekeeping/docker/kagome-dev/Makefile b/housekeeping/docker/kagome-dev/Makefile
--- a/housekeeping/docker/kagome-dev/Makefile
+++ b/housekeeping/docker/kagome-dev/Makefile
@@ -107,3 +107,49 @@ upload_apt_package:
 	gcloud config set artifacts/repository $(ARTIFACTS_REPO); \
 	gcloud config set artifacts/location $(REGION); \
 	gcloud artifacts apt upload $(ARTIFACTS_REPO) --source=./pkg/kagome-dev_$$(date +'%d.%m.%y')-$${SHORT_COMMIT_HASH}-$${BUILD_TYPE}_$(PACKAGE_ARCHITECTURE).deb
+	
+
+runtime_cache:
+	CONTAINER_NAME=kagome_dev_runtime_cache_$$(openssl rand -hex 6); \
+	RUNTIME_VERSION=$$(python3 get_wasmedge_version.py); \
+	DOCKER_EXEC_RESULT=0 ; \
+	echo "Runtime version: $$RUNTIME_VERSION"; \
+	docker run -d --name $$CONTAINER_NAME \
+		--platform $(PLATFORM) \
+		--entrypoint "/bin/bash" \
+		-e RUNTIME_VERSION=$$RUNTIME_VERSION \
+		-e PACKAGE_ARCHITECTURE=$(PACKAGE_ARCHITECTURE) \
+		-e GOOGLE_APPLICATION_CREDENTIALS=/root/.gcp/google_creds.json \
+		-v $$(pwd)/../../../../kagome:/opt/kagome \
+		-v $(GOOGLE_APPLICATION_CREDENTIALS):/root/.gcp/google_creds.json \
+		$(DOCKER_REGISTRY_PATH)zombie_tester:latest \
+		-c "tail -f /dev/null"; \
+	docker exec -t $$CONTAINER_NAME /bin/bash -c \
+		"cd /opt/kagome/zombienet && \
+		sed -i '1s/^#//' /etc/apt/sources.list.d/kagome.list && \
+		install_packages kagome-dev && \
+		./precompile.sh && \
+		mkdir -p /tmp/kagome_runtime && \
+		cp -r /tmp/kagome/runtimes-cache/* /tmp/kagome_runtime && \
+		cd /opt/kagome/housekeeping/docker/kagome-dev && \
+		./build_apt_package.sh \
+			\"$${RUNTIME_VERSION}\" \
+			$(PACKAGE_ARCHITECTURE) \
+			kagome-dev-runtime \
+			/tmp/kagome_runtime \
+			'Kagome Runtime Dev Debian Package' \
+			'kagome' ; \
+		" || DOCKER_EXEC_RESULT=$$? ; \
+	if [ $$DOCKER_EXEC_RESULT -ne 0 ]; then \
+		echo "Error: Docker exec failed with return code $$DOCKER_EXEC_RESULT"; \
+		docker stop $$CONTAINER_NAME; \
+		exit $$DOCKER_EXEC_RESULT; \
+	fi; \
+	docker stop $$CONTAINER_NAME
+
+
+upload_apt_package_runtime:
+	RUNTIME_VERSION=$$(python3 get_wasmedge_version.py); \
+	gcloud config set artifacts/repository $(ARTIFACTS_REPO); \
+	gcloud config set artifacts/location $(REGION); \
+	gcloud artifacts apt upload $(ARTIFACTS_REPO) --source=./pkg/kagome-dev-runtime_${RUNTIME_VERSION}_$(PACKAGE_ARCHITECTURE).deb
